import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Form from "@/Components/IndexPage/Form";
import Highlights from "@/Components/IndexPage/Highlights";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box backgroundColor="#EAEAEA" h="100vh" w="100%">
          <Form />
          <Highlights />
        </Box>
      </main>
    </>
  );
}
